context('Update Work Address page', () => {
  it('page will load and show all required fields', () => {
    cy.visit('/update-work-address/00000000-0000-0000-0000-600000000009')
    cy.url().should('include', '/update-work-address')
    cy.get('#description').should('exist').should('be.visible')
    cy.get('#buildingName').should('exist').should('be.visible')
    cy.get('#houseNumber').should('exist').should('be.visible')
    cy.get('#streetName').should('exist').should('be.visible')
    cy.get('#district').should('exist').should('be.visible')
    cy.get('#townCity').should('exist').should('be.visible')
    cy.get('#county').should('exist').should('be.visible')
    cy.get('#postcode').should('exist').should('be.visible')
  })

  it('will save all fields and redirect properly when Save is clicked', () => {
    cy.visit('/update-work-address/00000000-0000-0000-0000-600000000009')
    cy.url().should('include', '/update-work-address')
    cy.get('#description').type('A Description')
    cy.get('#buildingName').type('B Building Name')
    cy.get('#houseNumber').type('C House Number')
    cy.get('#streetName').type('D Street Name')
    cy.get('#district').type('E District')
    cy.get('#townCity').type('F Town City')
    cy.get('#county').type('G County')
    cy.get('#postcode').type('H AA11AA')
    cy.get('#save-button').should('exist').should('be.visible').click()
    cy.url().should('include', '/sign-and-send')
  })

  it('will return to sign and send screen when cancel is clicked', () => {
    cy.visit('/update-work-address/00000000-0000-0000-0000-600000000009')
    cy.url().should('include', '/update-work-address')
    cy.get('#cancel-button').should('exist').should('be.visible').click()
    cy.url().should('include', '/sign-and-send')
  })

  it('validation will trigger when none of description, number or name is present', () => {
    cy.visit('/update-work-address/00000000-0000-0000-0000-600000000005')
    cy.url().should('include', '/update-work-address')
    cy.get('#streetName').type('D Street Name')
    cy.get('#district').type('E District')
    cy.get('#townCity').type('F Town City')
    cy.get('#county').type('G County')
    cy.get('#postcode').type('H Postcode')
    cy.get('#save-button').should('exist').should('be.visible').click()
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.get('#description-error')
      .should('exist')
      .should('contain.text', 'At least 1 out of [Description, Building Name, Address Number] must be present')
    cy.get('#buildingName-error')
      .should('exist')
      .should('contain.text', 'At least 1 out of [Description, Building Name, Address Number] must be present')
    cy.get('#houseNumber-error')
      .should('exist')
      .should('contain.text', 'At least 1 out of [Description, Building Name, Address Number] must be present')
  })

  it('validation will trigger when street, town or postcode is left blank', () => {
    cy.visit('/update-work-address/00000000-0000-0000-0000-600000000005')
    cy.url().should('include', '/update-work-address')
    cy.get('#description').type('A Description')
    cy.get('#buildingName').type('B Building Name')
    cy.get('#houseNumber').type('C House Number')
    cy.get('#district').type('E District')
    cy.get('#save-button').should('exist').should('be.visible').click()
    cy.get('.govuk-error-summary__title').should('exist').should('contain.text', 'There is a problem')
    cy.get('#streetName-error')
      .should('exist')
      .should('contain.text', 'Street Name : This is a required value, please enter a value')
    cy.get('#townCity-error')
      .should('exist')
      .should('contain.text', 'Town/City : This is a required value, please enter a value')
    cy.get('#postcode-error')
      .should('exist')
      .should('contain.text', 'Postcode : This is a required value, please enter a value')
  })
})
