---
# Per environment values which override defaults in hmpps-suicide-risk-form-ui/values.yaml

generic-service:
  ingress:
    host: suicide-risk-form.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://suicide-risk-form.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    NDELIUS_DEEPLINK_URL: "https://ndelius.probation.service.justice.gov.uk/NDelius-war/delius/JSP/deeplink.xhtml"
    SUICIDE_RISK_API_URL: "https://suicide-risk-form-api.hmpps.service.justice.gov.uk"
    ASSESS_RISKS_AND_NEEDS_API_URL: "https://assess-risks-and-needs.hmpps.service.justice.gov.uk"
    PROBATION_OFFENDER_SEARCH_API_URL: "https://probation-offender-search.hmpps.service.justice.gov.uk"
    NDELIUS_INTEGRATION_URL: "https://suicide-risk-form-and-delius.hmpps.service.justice.gov.uk"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - unilink_staff
      - probation # for production staff

generic-prometheus-alerts:
  alertSeverity: hmpps-suicide-risk-form-notifications
