---
# Per environment values which override defaults in hmpps-suicide-risk-form-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: suicide-risk-form-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://suicide-risk-form-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    NDELIUS_DEEPLINK_URL: "https://ndelius.test.probation.service.justice.gov.uk/NDelius-war/delius/JSP/"

  allowlist:
    groups:
      - internal
      - unilink_staff
      - moj_cloud_platform # for end-to-end testing

generic-prometheus-alerts:
  alertSeverity: hmpps-suicide-risk-form-notifications
